name: RegionRotation
main: net.projectzombie.regionrotation.main.Main
version: 1.0
depend: [WorldEdit,WorldGuard]
commands:
  rr:
    description: Full suite of Region Rotation cmds.
    usage: "/rr <add:addalt:remove:reset:rotate"
